// Generated by CoffeeScript 1.7.1
(function() {
  var amqp, heroku, rabbitMQ;

  amqp = require('amqplib/callback_api');

  heroku = require('../../../etc/heroku');

  rabbitMQ = heroku.config.rabbitMq.connect.toString();

  exports.send_msg = function(que, msg, done) {
    console.log('Sending msg to Queue %s: ', que);
    return amqp.connect(rabbitMQ, function(err, conn) {
      if (err != null) {
        console.log(err);
        return done(err, null);
      } else {
        return conn.createChannel(function(err, ch) {
          if (err != null) {
            console.log(err);
            return done(err, null);
          } else {
            return ch.assertQueue(que, {
              durable: true
            }, function(err, ok) {
              if (err != null) {
                console.log(err);
                return done(err, null);
              } else {
                ch.sendToQueue(que, new Buffer(msg, {
                  persistent: true
                }));
                return setTimeout((function() {
                  conn.close();
                  return done(null, ok);
                }), 1000);
              }
            });
          }
        });
      }
    });
  };

}).call(this);
